### ISSUE TITLE
npm install times-out

### ISSUE THREAD

**Issue by ronaaron** [pure-css/pure#1020]
Using npm 8.12.1, and the latest pure-css source, I run `npm install` in the pure directory, and get:

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npm.vzbuilders.com:4443/npm-registry/api/npm/npm-registry/zip-stream/-/zip-stream-4.0.4.tgz failed, reason: connect ETIMEDOUT 217.146.190.11:
```

I've had the same problem for a few weeks, I assume it means that site isn't available?

**Comment by CoreSec-xyz** [comment]
I can confirm that the solusion is in Pull request #1002

**Comment by michaelbutler** [comment]
It still times out for me. The way to fix it was to delete `package-lock.json`, since that is where vzbuilders.com is referenced. By deleting that file, when I run `npm install` it downloads the packages from the standard npm registry, not vzbuilders, which I assume is some verizon or yahoo thing.

**Comment by redonkulus** [comment]
This is correct. The lock file has our internal registry. I will generate a new lock file using the open source registry. 

Feel free to open a new PR with an updated lock file too.

**Comment by redonkulus** [comment]
I’ve removed the invalid lock file from the source. I will re-add a valid one later.

**Comment by redonkulus** [comment]
@ronaaron a new package-lock.json was added without the internal registry. Please try again.
