### ISSUE TITLE
Switch CDN provider in documentation

### ISSUE THREAD

**Issue by ayuhito** [pure-css/pure#1033]
I think it'd be appropriate for pure to move away from promoting usage of unpkg to an alternative like jsDelivr. 

unpkg is unmaintained and [full of issues](https://github.com/mjackson/unpkg/issues). On the other hand, [jsDelivr](https://www.jsdelivr.com/) is actively maintained and offers more reliability due to its [fallback system](https://www.jsdelivr.com/network/infographic).

I'd be more than happy to make a PR changing all references of unpkg if the team believes it's appropriate to switch.

**Comment by redonkulus** [comment]
We do mention jsDelivr on the Customize page for combo URLs. I'm fine migrating from unpkg.com to jsDelivr if unpkg is unmaintained.

Do you want to open a PR to migrate the code?

**Comment by ayuhito** [comment]
Sure thing, I'll be happy to do so in a couple of hours.
