### ISSUE TITLE
Class name conventions

### ISSUE THREAD

**Issue by adapterik** [pure-css/pure#104]
The docs state that the Pure way of creating submodules for module `pure-mymodule` is to create a class `pure-mymodule-mysubmodule` and to use such a submodule selector to provide "specific rules that apply to [the submodule]". In the css the selector would look like `.pure-mymodule-mysubmodule` and in the html the class would include `pure-mymodule pure-mymodule-submodule`.

This will work for new proerties introduced in submodules, but if the submodule is overriding module defaults, won't this provide inconsistent results? Wouldn't requiring the `pure-mymodule` as a prefix to the submodule be required in order to ensure overriding? Thus the first part of a selector for any submodule would be `.pure-module.pure-module-submodule`. Within Pure itself both types of selectors are used, at least in my experience with Menu.

**Comment by redaxmedia** [comment]
There is an great alternative called [NCSS]( https://ncss.io).
