### ISSUE TITLE
composer require incorrect.

### ISSUE THREAD

**Issue by joshespi** [pure-css/pure#1272]
this file
https://github.com/pure-css/pure/blob/master/site/src/pages/tools/index.js

currently says "composer require pure-css/purecss". I believe "composer require yahoo/purecss" is correct.  this caused me confusion when getting started.

thanks!

**Comment by guest20** [comment]
Might it be `pure-css/pure` (the name of thus repo)?

**Comment by joshespi** [comment]
Correct, however if someone is following the documentation on the website like I was, that package does not exist. I dug around a bit to find what I believe is the Correct one based on contributors.

**Comment by redonkulus** [comment]
Thank you for filing this, I've fixed it in https://github.com/pure-css/pure/commit/9782a243cad7432a8975ac5f0bb6ab29b82e98b0
