### ISSUE TITLE
Browsing to project website fails with ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jaese** [pure-css/pure#1371]
**Describe the bug**
Browsing to the project website (https://pure-css.github.io/, http://purecss.io) fails with ERR_TOO_MANY_REDIRECTS on Chrome.

It seems to bounce between pure-css.github.io and purecss.io

**To Reproduce**
1. Go to https://pure-css.github.io/ on Chrome

**Expected behavior**
View the documentation

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome, safari

**Comment by stevehav** [comment]
Having the same problem here

**Comment by guest20** [comment]
Just in case it helps:

You can see docs for pre-1.0 releases at https://versions.bulma.io/

Also the 0.9.4 links is busted but you can still see the docs for 0.9.4 it at https://versions.bulma.io/0.9.4/

**Comment by redonkulus** [comment]
Thanks for the report, it should be fixed now. I had changed a setting the other day but it didn't get updated properly.
