### ISSUE TITLE
How can I pull right a column?

### ISSUE THREAD

**Issue by shillo92** [pure-css/pure#165]
Hi,

I have a layout which has a logo to the right and a menu to the left. If I simply apply an "align: left" rule to the menu it starts to break bad when I minimize the screen.

What is the best way to accomplish this in PureCSS?

**Comment by yyil** [comment]
Any news of this? Will this be supported?

**Comment by pimbrouwers** [comment]
https://github.com/pimbrouwers/Pure-CSS-Push-Pull-Library

Enjoy :)

p.s. keep in mind if you want to use this with an element other than a div, you'll need to add the appropriate selector modification.
