### ISSUE TITLE
Print view uses responsive layout

### ISSUE THREAD

**Issue by blicksky** [pure-css/pure#237]
I am using Pure responsive grids to build a page that is responsive for desktop and mobile clients, but needs to use the desktop layout for printing. After some experimentation, primarily with Chrome's print preview, it seems as if when printing, the responsive layout is being applied. Using a local copy of grids-r.css, I was able to change the behavior by changing only

``` css
@media (max-width: 767px) {
...
}
```

 to

``` css
@media screen (max-width: 767px) {
...
}
```

This suggests that the screen width that Chrome uses when rendering the print preview is somewhere in between 480px and 767px.

Without making a change to grids-r.css, the only other option I could come up with is to include a stylesheet that only applies to `media="print"`, and includes all of the `pure-u-*` rules with !important so that they take precedence over the `width: 100%` being applied in the grids-r.css `@media` queries. I'd appreciate any other suggestions on how to accomplish this.

Is print layout something that Pure wishes to concern itself with? Would updating all the @media queries in grids-r.css to only apply to "screen" clients be an appropriate change?

**Comment by redonkulus** [comment]
Closing out issues that will not be worked on. If the community wants to contribute PRs, I'm more than willing to review them. Thanks!
