### ISSUE TITLE
Remove gradient backgrounds from buttons?

### ISSUE THREAD

**Issue by stevenvachon** [pure-css/pure#276]
They're annoying to override. The simpler the framework, the easier it is to work with.

**Comment by xemexpress** [comment]
This works for me:

HTML
<button class="btn other-styles">Button</button>

CSS
.btn {
  border: 1px solid transparent;
}

.other-styles {
  border-color: tomato;
}

**Comment by redonkulus** [comment]
Gradients are fine the way they are, they can always be overwritten by the application.
