### ISSUE TITLE
request for multiline ellipsis

### ISSUE THREAD

**Issue by ItsAsbreuk** [pure-css/pure#309]
this is pretty complicated, but it would be awesome if we could make a div doing this by just add a classname like <code>pure-ellipsis</code>

To illustrate the purpose: http://theamazingweb.net/2013/01/29/pure-css-multiline-text-with-ellipsis/

**Comment by jamesalley** [comment]
Multi-line ellipsis is definitely harder than it should be. I agree this warrants a helper class. I'm keeping this issue open.

**Comment by redonkulus** [comment]
Wait long enough and the browsers fix it for us. [`line-clamp`](https://css-tricks.com/almanac/properties/l/line-clamp/) can be used for this now. With pretty good [browser support](https://caniuse.com/#search=line-clamp) (except IE 11).
