### ISSUE TITLE
Offsetting Grid Units

### ISSUE THREAD

**Issue by danecando** [pure-css/pure#318]
Is there any plan to add offsets to the grid to create spacing in between units?

**Comment by ullalaaron** [comment]
Just wondering if 6 years later things have changed.... are you sure that having to add a fake placeholder like @jlbruno demonstrated is the best way to handle this?
I really think that adding offset support would be a great feature

**Comment by lkraav** [comment]
I'm fairly certain this is a job for either

* CSS Grid
* Upcoming flex gap https://caniuse.com/#feat=flexbox-gap
