### ISSUE TITLE
Marketing layout header appears on two lines in Chrome.

### ISSUE THREAD

**Issue by nimser** [pure-css/pure#320]
I just downloaded the marketing layout and this is what I obtain in Chrome (tried with versions 32 and 34):

![marketing layout screenshot](http://i.imgur.com/eJ9uQmH.png)

Clues:
- My screen resolution is 1680*1050
- The layout renders as expected (menu on one line) in Firefox
- The layout renders as expected when loading the [hosted demo](http://purecss.io/layouts/marketing/) instead of the code downloaded from [the official page](http://purecss.io/layouts/marketing/download).
- The layout will randomly render as expected when loading in Chrome (after refreshing maybe 20 times)
- Resizing the window to very small and then back to maximized fixes the issue
- removing the `<input type="password">` field from the source fixes the issue
- adding / removing other fields from the source does _not_ fix the issue

The last two seem very awkward to me. I've minimized the source to the following minimal failing example:

``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Landing Page</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure.css">
  <link rel="stylesheet" href="css/layouts/marketing.css">
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="#">Your Site</a>
        <ul>
            <li class="pure-menu-selected"><a href="#">Home</a></li>
            <li><a href="#">Tour</a></li>
        </ul>
    </div>
</div>

<div class="content-wrapper">
  <div class="content">
    <form class="pure-form pure-form-stacked">
        <fieldset>
            <input type="password">
        </fieldset>
    </form>
  </div>
</div>
</body>
</html>
```

Replacing `type="password` by `type="text"` (or anything else) in this failing example makes the header render properly.

Can anyone confirm this? Any clue where the problem lies?

**Comment by fliiiix** [comment]
Any update on this?
