### ISSUE TITLE
Will Pure get to 1.0?

### ISSUE THREAD

**Issue by grantmcconnaughey** [pure-css/pure#357]
Hello. I'm wondering if we will ever seen Pure get to version 1.0.

Development has been more or less stagnant for the last 4 and a half months, with the only commits being a font awesome version bump and the 0.5.0 release. Is there work going on behind the scenes that aren't being pushed to Github, or have there really not been any commits in all that time?

I really love Pure. I use it in almost all of my projects. It would be a real shame to see it become abandonware.

Thanks for reading!

**Comment by redonkulus** [comment]
@grantmcconnaughey many years later Pure is now at 1.0 ... better late then never I suppose.
