### ISSUE TITLE
grids spacing wrong without Arial on pure-g, pure-g-r

### ISSUE THREAD

**Issue by adapterik** [pure-css/pure#41]
This was reported on yui3 grids and still exists (http://yuilibrary.com/projects/yui3/ticket/2533215.) 
The summary is that the letter spacing = -0.31em hack placed on the pure-g[-r] class to make the grid units work well only works (well) if the font family is Arial. It may _appear_ to work for other font families (pure sets the font family for the html tag to sans-serif), but the spacing is not perfect, and it breaks down in certain browsers (atm it fails on FF/Linux for me.) The general solution is ensure that the pure-g and pure-g-r divs get Arial, and that your own content within the pure-u-x-x divs get whatever font you want (so I guess that means resetting back to sans-serif for pure compatibility.)
My interrim solution is to add css like this

```
.pure-g, .pure-g-r {
    font-family: Arial;
}
```

in my own css file loaded after pure, and also either resetting the font for all the pure-u-x-x

```
.pure-u-1, .pure-u-1-2, ...
    font-family: sans-serif;
}
```

or using a container (which I always do anyway) inside the pure-u-x-x which sets the font (and does other as well.)

I think the best solution is to handle the pure-g, and pure-u stuff inside of pure.

**Comment by ckizer** [comment]
I'm still getting this issue in safari. I added the code to the bottom of my stylesheet:

```
/* Putting the font-family to Arial makes sure the
letter and word spacing collapsing works */
.pure-g,
.pure-g-r {
    font-family: "Helvetica", "Arial", sans-serif;
}

/* Declaring the font-family on the children ensures
that the grid doesn't flow to a new line. */
.pure-g [class *= "pure-u"],
.pure-g-r [class *= "pure-u"] {
  font-family: 'Neue';
}


```

**Comment by stuartlamour** [comment]
please don't hardcode font stacks in a plugin.

**Comment by stuartlamour** [comment]
ever.

**Comment by esr360** [comment]
Setting the following CSS will fix the whitespace issue in between columns in Webkit browsers regardless of typeface:

```css
.pure-g,
.pure-g-r {
    display: table;
    width: 100%;
}
```

Combined with the previous letter-spacing hack that works with IE and Firefox, you can get inline-block columns that work perfectly in all browsers except Opera:

https://github.com/esr360/Kayzen-GS#solving-the-whitespace-issue

http://esr360.github.io/Kayzen-GS/

As far as I can tell, apart from the slight mis-calculations Opera causes on the columns, there's no real downside to this method.

**Comment by SimonPersson** [comment]
This is still broken on Ubuntu 14.04 Server Edition with Firefox 39:
![broken](https://cloud.githubusercontent.com/assets/606973/8847320/f312e54c-312d-11e5-8159-94464790976e.png)

To reproduce, install Ubuntu 14.04 Server Edition with a basic window manager (I use DWM, but I bet any window manager that doesn't pull in extra fonts will work) and Firefox. Load a basic test page, like:
```html
<html>
	<head>
		<title>Pure CSS broken grids.</title>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
	</head>
	<body>
		<div class="pure-g">
			<div class="pure-u-1-3">Thirds</div>
			<div class="pure-u-1-3">Thirds</div>
			<div class="pure-u-1-3">Thirds</div>
		</div>
	</body>
</html>
```
And watch the third column end up on a new row.

The issue is resolved when the `gsfonts` package is installed.
