### ISSUE TITLE
`.pure-table-bordered` don't work when td has rowspan attribute on ie11,firefox 35

### ISSUE THREAD

**Issue by happytor** [pure-css/pure#432]
<table class="pure-table pure-table-bordered">
<thead>
<tr>
<th>Id</th>
<th>Name</th>
</tr>
</thead>
<tbody>
<tr>
<td rowspan="3">
1
</td>
<td>Tom</td>
</tr>
<tr>
<td>Jerry</td>
</tr>
<tr>
<td>John</td>
</tr>
</tbody>
</table>

![a](https://cloud.githubusercontent.com/assets/1264899/6053369/6cdced12-ad19-11e4-82b8-d2d535d3a945.png)

**Comment by jamesalley** [comment]
Great issue, thanks for bringing it to my attention. 

I will mark this as a bug. We may be able to remove this declaration block:

.pure-table td:first-child,
.pure-table th:first-child {
    border-left-width: 0;
}

But I'll need to do a lot more testing before I'm confident that's the right thing to do.

If you need a fast fix, create a custom class to set that border width to 1px.

**Comment by jamesalley** [comment]
I've added this case to our test files, so it will get checked out in the future.

Also, I created a JSFiddle for reference:

http://jsfiddle.net/james_alley/vk97p2xo/

**Comment by Guard13007** [comment]
This also happens with a colspan. Any idea when this might get fixed? It's been like a year.

**Comment by wattswing** [comment]
Hi there, anything :up: with this annoying **bug** ?

> We may be able to remove this declaration block:
> 
> .pure-table td:first-child,
> .pure-table th:first-child {
> border-left-width: 0;
> }

Too bad. I just realized that too, but the FW seems to count on this.
> do a lot more testing before I'm confident that's the right thing to do.

:trollface:

**Comment by lkraav** [comment]
After playing around a bit w/ http://jsfiddle.net/james_alley/vk97p2xo/ I would suggest dropping those complicated side/bottom adjustments, and just going with:

```css
.pure-table td, .pure-table th { 1px solid #cbcbcb; }
```

I think what's currently there will not work out no matter how you wrestle it.

**Comment by magikstm** [comment]
This should be considered. Issue is still present in Firefox and IE11.
