### ISSUE TITLE
Printing grid elements: cut off at page end 

### ISSUE THREAD

**Issue by mbelow** [pure-css/pure#467]
I have noticed that grid elements can't be printed well by the browsers I have tried. Iceweasel (comparable to Firefox 31.5) cuts them off at the end of the first page, Chrome and Opera try to let the content run onto following pages, but they sometimes cut lines at page end in half.

Blogs indicate that it is a problem that these elements are styled as

```
display: inline-block;
```

which means that can't be spread onto multiple pages easily.

It seems to help Firefox to declare a stylesheet for `media=print` that contains just

```
 .pure-u-1, .pure-u-1-1, .pure-u-1-2, .pure-u-1-3, .pure-u-2-3, .pure-u-1-4, .pure-u-3-4, .pure-u-1-5,  .pure-u-2-5, .pure-u-3-5, .pure-u-4-5, .pure-u-5-5, .pure-u-1-6, .pure-u-5-6, .pure-u-1-8, .pure-u-3-8, .pure-u-5-8, .pure-u-7-8, .pure-u-1-12, .pure-u-5-12, .pure-u-7-12, .pure-u-11-12, .pure-u-1-24, .pure-u-2-24, .pure-u-3-24, .pure-u-4-24, .pure-u-5-24, .pure-u-6-24, .pure-u-7-24, .pure-u-8-24, .pure-u-9-24, .pure-u-10-24, .pure-u-11-24, .pure-u-12-24, .pure-u-13-24, .pure-u-14-24, .pure-u-15-24, .pure-u-16-24, .pure-u-17-24, .pure-u-18-24, .pure-u-19-24, .pure-u-20-24, .pure-u-21-24, .pure-u-22-24, .pure-u-23-24, .pure-u-24-24 {
display: inline ;
} 
```

For Chrome and Opera, this extra stylesheet has no visible effect.

**Comment by jamesalley** [comment]
I've noticed printing from a web browser has almost never been a good experience ever since the dawn of the web. But that's no excuse, we should try to improve printing if we can and the cost is not too great. I'll leave this issue open for later consideration.

**Comment by romecode** [comment]
@mbelow oh man! I must have spent a whole day until I finally decided to pull the problematic code and isolate it away from purecss. Once I realized it was pure, well a quick search on github and here we are, your @media css fix definitely takes care of the problem. 

what a PITA! thanks again
