### ISSUE TITLE
form elements with chinese characters is malposed on Chrome

### ISSUE THREAD

**Issue by weijarz** [pure-css/pure#478]
On Chromium 42.0.2311.90 (64-bit) / ArchLinux
The form elements with chinese characters is malposed.
[Check this codepen](http://codepen.io/weijarz/pen/EjaNPj)

**Comment by redonkulus** [comment]
@weijarz can you explain more what the issue it? It looks ok to me on Chrome 54.

**Comment by weijarz** [comment]
@redonkulus Buttons that contains chinese characters are higher than engligh.

Pure:
![screenshot from 2016-11-22 15-41-46](https://cloud.githubusercontent.com/assets/8944061/20515056/ae261d8c-b0ca-11e6-87b8-764da143a939.png)

Bootstrap:
![screenshot from 2016-11-22 15-42-55](https://cloud.githubusercontent.com/assets/8944061/20515065/b67768d8-b0ca-11e6-8bf6-217f518336de.png)

**Comment by redonkulus** [comment]
@weijarz is this only an issue on Linux or do you see this on other environments too? Would be interesting to see if Bootstrap handles this differently or its just some line-height browser difference.

**Comment by Goury** [comment]
Firefox 50 with Ubuntu 16.04 work fine.
Chromium 53 renders chinese buttons bigger than it should.

**Comment by redonkulus** [comment]
Thanks for the info. This will need more debugging, if anyone in the community can help, that would be great.
