### ISSUE TITLE
Consider adding new rules for ABBR

### ISSUE THREAD

**Issue by jamesalley** [pure-css/pure#513]
In Firefox, ABBR has twin dotted lines under it. To make this consistent across browsers, we should consider adding the following, or similar (pending testing):

```
abbr[title] {
    border-bottom: 1px dotted; // to match normalize
    text-decoration: none; // to strip out unique Firefox formatting resulting in double dashed line
    cursor: help; // to make consistent with Safari. Examine other browsers to be sure.
}
```

**Comment by redonkulus** [comment]
We should probably upgrade to the latest version of Normalize to solve this issue: https://github.com/yahoo/pure/issues/663#issuecomment-317292616

But this requires more testing.

**Comment by redonkulus** [comment]
v2.0.0 of Pure is on the latest version of Normalize.css, this should be fixed now.
