### ISSUE TITLE
pull right for horizontal menus

### ISSUE THREAD

**Issue by mseri** [pure-css/pure#56]
Creating a flexible space using inline-blocks seems impossible and the justify trick seems not to work.

I played around with the following code but it increases slightly the height of my fixed horizontal menu bar:

```
.pure-menu-custom-pull-right {
  text-align: justify;
}

.pure-menu-custom-pull-right:after {
  content: '';
  display: inline-block;
  width: 100%;
  height: 0;
  font-size:0;
  line-height:0;
  margin: 0;
  padding: 0;
}
```

Is there a way to add a pull-right for the menus, I think it could be a useful addition to the standard base?

**Comment by josemrb** [comment]
+1

**Comment by martylamb** [comment]
+1

**Comment by jamesalley** [comment]
Lots of +1 here but no clean way to do it yet...I'll consider how to do this in a future release.

**Comment by jamesalley** [comment]
I was just checking on what bootstrap does, because often it's a feature in bootstrap that inspires people to request something of Pure...and Bootstrap just offers this:

```
.pull-left {
  float: left !important;
}
.pull-right {
  float: right !important;
}
```

I would never rush to add something like that to Pure! One, applying such a class would not magically solve the problems (including bi-di issues and problems with alignment) mentioned in this thread. And it introduces an `!important`, always a red flag.

**Comment by jamesalley** [comment]
This would be my recommended solution. Perhaps folks can try out something like this and let me know how it works for you. Note that semantically it works for either RTL or LTR contexts.

```
.pure-pull-end {
    float: right;
}
    [dir="rtl"] .pure-pull-end {
        float: left;
    }
.pure-pull-start {
    float: left;
}
    [dir="rtl"] .pure-pull-start {
        float: right;
    }
```

**Comment by lae** [comment]
I was able to achieve this effect using flexbox:
```
.pure-menu-horizontal .pure-menu-list {
    display: inline-flex;
    width: 100%;
}
.pure-menu-item-separator {
    flex-grow: 1;
}
```
(and then have an <li> using the above separator class in between the wanted elements)

Maybe we can use that in Pure?

**Comment by jamesalley** [comment]
I'll try it when I actively develop this feature and test it across browsers.

**Comment by zevero** [comment]
One year later it still is a nice to have.
I did not succeed to use the elegant solution proposed by @lae . The right menu only starts right from the display and a scroll bar appears...

I tested proposal from @jamesalley but I found that I need to do

    .pure-menu-horizontal .pure-menu-list {display:block}
    .pure-pull-end {
        float: right;
    }
    [dir="rtl"] .pure-pull-end {
        float: left;
    }

Which results in pure-menu-heading beeing on a seperate line ... which I do not mind for now. But it is not intended...

Will this feature be tested and integrated?

**Comment by RoboSparrow** [comment]
A workaround would be to put the menu in separated lists as columns under the `.pure-g` grid. Both the  `.pure-menu-horizontal` menu lists and the grid column classes (i.e. `.pure-u-sm-1-3` etc) are inline-block elements. The menu items have no width by default so they can safely inherit the width from the column classes. 

```
<!DOCTYPE html>
<html>
  <head>
        <meta charset="UTF-8">
        <title>Right aligned menu item in Pure Css</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
        <style>
        /* media query for pure-u-sm-* classes from grids-responsive.css */   
        @media screen and (min-width: 35.5em) {
            .pure-menu-horizontal.sm-right{
                text-align: right;
            }
        }
        </style>    
    <body>

        <div class="pure-g">
            <div class="pure-menu pure-menu-horizontal pure-u-1 pure-u-sm-4-5">
                <a href="#" class="pure-menu-heading pure-menu-link">BRAND</a>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">News</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Sports</a></li>
            </div>
            <div class="pure-menu pure-menu-horizontal pure-u-1 pure-u-sm-1-5 sm-right">
                <ul class="pure-menu-list">
                    <li class="pure-menu-item">
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Finance</a></li>
                    </li>
                </ul>
            </div>
        </div>

    </body>
</html>
```

**Comment by jharaphula** [comment]
In this example I have tabs like Home, About Us, Services, News & Career. You can add or update tags as you want. This menu is supporting sub menu feature. Under About Us & Services I added some sub menu items for demo purpose. Technically to design this horizontal menu I used UL element of HTML. Using pure CSS I am defining color & theme to the menu. For responsive I used CSS3 media queries. In media query I configured the menu max-width to 750px. 750px is nothing but the total width of my horizontal menu (including all tabs)... https://goo.gl/VwTusI

**Comment by jwinnie** [comment]
What is the status on this issue now?

**Comment by redonkulus** [comment]
@jwinnie could this just be a solution for css grids or flex-box? Doesn't seem like Pure needs to support this natively anymore.
