### ISSUE TITLE
pure-form-aligned with radio buttons

### ISSUE THREAD

**Issue by slisznia** [pure-css/pure#614]
### Description

When creating an aligned form with radio buttons, the labels surrounding the input-radio buttons get formatted incorrectly.

### Expected behavior
It should be possible to create an aligned-form with radio buttons one under another or inline. Example:

```
My choices:  ( ) choice A   ( ) choice B

Or:

My choices:  ( ) choice A
             ( ) choice B
```

### Actual behavior
The label of the input-radio gets formatted with 10em width. The reason this happens is that when using radio/checkbox input types, the \<label\> tag is used both to name the choice (ie "choice A") and to name the choice-group (ie "My choices").

### Workaround

I've overridden the label styling to only apply to the first child, and leave the rest on auto:
```
.pure-form-aligned .pure-control-group label:first-child {
	width: 10em;
}

.pure-form-aligned .pure-control-group label:not(:first-child) {
	width: auto;
}
```

**Comment by redonkulus** [comment]
@slisznia can you provide a demo example so I can see it live?

**Comment by slisznia** [comment]
Here you go -- without applying any workarounds: https://jsfiddle.net/x35Lq8sk/

Look how spaced out are the radio-options. They also don't react well when fitted on a narrow screen.

**Comment by I-CRE8** [comment]
What would be really nice is the ability to have radio buttons and checkboxes aligned like this example http://www.i-cre8.com/test-files/css-form/index.html

**Comment by redonkulus** [comment]
@slisznia I [modified your fiddle](https://jsfiddle.net/y7wm94ur/) slightly to use a `<legend>` tag instead of another `<label>` as the header. I had to add some custom styles for the `<legend>` to achieve this. However, the radio buttons are still not aligned to the right of it, need to figure out why. 

Oddly enough, I tried to use a `<fieldset>` to wrap the radio buttons but that made the `<legend>` align to the right.

**Comment by I-CRE8** [comment]
Something like this perhaps ? https://jsfiddle.net/i_cre8/8hj6gawz/

**Comment by slisznia** [comment]
@I-CRE8 better, but doesn't respond well to different layouts. Examples
![edit fiddle - jsfiddle - google chrome_295](https://cloud.githubusercontent.com/assets/1666246/25903809/1516abfc-3563-11e7-8760-ee7dd50b5a55.png)
![edit fiddle - jsfiddle - google chrome_296](https://cloud.githubusercontent.com/assets/1666246/25903814/1878f5ac-3563-11e7-97db-0a9f72db881f.png)

**Comment by I-CRE8** [comment]
@slisznia fair point, I hadn't thought about responsiveness. I'll work some more on this as time allows.

**Comment by toastbrotch** [comment]
anyone found a workaround or solution to fix this? it seems to me that the proposed workaround in the first post does not work in the jsfiddle in second answer...

**Comment by toastbrotch** [comment]
after some experiments i went with this solution... just in case someone needs more inspiration...
```
<div class="pure-control-group" style="padding: .1em 0;">
  <label for="checkbox7" style="vertical-align: top;">checks</label>
  <div style="display: inline-block;">
      <label for="checkbox7-4" class="pure-checkbox" style="text-align: left; width: 100%"><input id="checkbox7-4" name="checkliweck[]" value=" blad sdfsdfds fsfd" type="checkbox"> blad sdfsdfds fsfd</label><br />
      <label for="checkbox7-5" class="pure-checkbox" style="text-align: left; width: 100%"><input id="checkbox7-5" name="checkliweck[]" value="fosel sdfdsfdfs" type="checkbox">fosel sdfdsfdfs</label><br />	
   </div>
</div>
```

**Comment by markasoftware** [comment]
The simplest solution I've found is to write the markup like this:

```html
<div class="pure-control-group">
    <label for="edit_profile4" style="">Gender</label>
    <div id="aoeu" class="pure-radiogroup">
        <label for="edit_profile4" class="pure-radio">
            <input type="radio" name="edit_profile4" value="0">Male</label>
        <label for="edit_profile4" class="pure-radio">
            <input type="radio" name="edit_profile4" value="1">Female</label>
        <label for="edit_profile4" class="pure-radio">
            <input type="radio" name="edit_profile4" value="2" checked="T">Classified</label>
    </div>
</div>
```

And add:

```css
.pure-radiogroup {
    display: inline-block;
}
```

And modify Pure's built-in rules so that it switches to `display: block` when on mobile (the default rule only does it for `, and also add a `:not(.pure-radio):not(.pure-checkbox)` filter on the `.pure-form-aligned .pure-control-group label` rule.
