### ISSUE TITLE
Reverse grid order

### ISSUE THREAD

**Issue by boyanraichev** [pure-css/pure#630]
There are often cases when in my work I need certain content on the right on a multicolumn layout (like a map, for example), but would prefer to have it on top on mobile in single column. With the current grid it is not possible to change the order of the elements, so if maybe other people also think it's a useful addition, some basic support can be added to Pure.

This can be achieved very easily with flex-direction, for example with single-use classes:
```
pure-g-reverse-column {
flex-direction: column-reverse;
}
pure-g-reverse-row {
flex-direction: row-reverse;
}

```

That way the developer can reverse the order for single-column or multi-column versions of the layout. I think media queries would be an overkill here, as most use-cases will be single vs multi column.

**Comment by boyanraichev** [comment]
Hmm I just noticed that in Safari row-reverse is ignored in single column layouts, but column-reverse is not ignored in multi column layouts. Thus, one can just order the elements as needed in single column and use row-reverse to reverse them in multi-column. But for more complicated use-cases some basic media queries would be needed.

**Comment by adrexia** [comment]
This is a great idea! We've been using this module to get around this problem, but we have to manually edit the push pull classes if we create a new grid size: https://github.com/pimbrouwers/YUI-Pure-CSS-Extensions

90% of our use case is to reorder for mobile/desktop.

**Comment by boyanraichev** [comment]
Actually, I ended up doing something else. I figured that with Pure you miss some nice CSS features. But I still love Pure's simplicity and elegance. With 97+% support for Flexbox already, I just created a new framework, that has logic similar to Pure, but is using flexbox. No more inline-blocks, no more font and letter spacing hacks. Very lightweight and very versatile. I have precious things like reverse flow direction, alignments in all possible ways, auto-grow for elements to fill up the space present, etc. And I can even use [order]([url](https://developer.mozilla.org/en/docs/Web/CSS/order)) for rearrangement of elements in every way I need. I will put it on GitHub soon. There are a few other flexbox frameworks already, but they are needlessly complicated and this is what I always liked about Pure - its minimalism.

This is the road Pure should have taken already, but it seems to me it's never making it out of Yahoo to the public domain and thus it's not going to get major developments at all.

**Comment by Crolug** [comment]
@boyanraichev Care to share this framework with us? :) Also, have you considered to update it for CSS Grid Layout as well?

**Comment by boyanraichev** [comment]
I have been busy at work, but I will do it this month for sure. I've already used it on several sites I'm building and flexbox works very well on all browsers! One great little thing is that, unlike when using inline-blocks and font spacing hacks, now every element can be a unit and a container at the same time. This makes the html code much cleaner!
 
CSS grid looks powerful, but support is only at 40% so far... Maybe in 3-4 years :)

**Comment by boyanraichev** [comment]
@Crolug @adrexia 
I've started setting up a github repo. I've already used this on 4-5 sites and it's been great switching to flexbox - it really simplifies things a lot. If you take a look / play with it etc - it would be great to hear your feedback.
[https://github.com/talkingaboutthis/tat-css/blob/master/src/tat.css]

**Comment by redonkulus** [comment]
Looks like a user land solution was created. Unless the community believes this is necessary in the framework, I'm not convinced yet, I'm going to close this out.
