### ISSUE TITLE
Usage of depricated overflow-scrolling and overflow-style CSS properties

### ISSUE THREAD

**Issue by apvarun** [pure-css/pure#635]
### Description

-webkit-overflow-scrolling and -ms-overflow-style have been removed from the w3 specification. All the browsers also have stopped supporting it. But the property is used to make the horizontal menu scrollable.

### Expected behavior
- Menu is scrollable only in mobile

### Actual behavior
- Menu should be scrollable if the list is long, even in desktop.

### Environment
* Pure version: v0.6.0

**Comment by redonkulus** [comment]
@apvarun for the Actual behavior, are you saying it doesn't scroll anymore?

**Comment by apvarun** [comment]
It works perfectly with a touchpad. But doesn't with a mouse scroll.

**Comment by redonkulus** [comment]
@apvarun looking at old tickets, whats the preferred way to do it now?

**Comment by apvarun** [comment]
@redonkulus I don't think we have a solution for this problem yet in CSS. But in the example for horizontal scroll, it's hard to detect that the area has a scroll by just looking at it.

For now, I think it's best to add note suggesting users to use a JS based solution if they want drag by mouse click. A similar note is present in [Dropdown](https://purecss.io/menus/#dropdowns) section as well.

**Comment by redonkulus** [comment]
This is fixed in https://github.com/pure-css/pure/commit/da4bf6b46ae4d9419d07e17ac7ce79c518e45847 and released in [v2.0.1](https://github.com/pure-css/pure/releases/tag/v2.0.1)
