### ISSUE TITLE
Marketing example layout menu displays funny in Firefox

### ISSUE THREAD

**Issue by thomasjm** [pure-css/pure#644]
### Description

In the layout example here: https://purecss.io/layouts/marketing/

I noticed that in Firefox, the menu is wrapped:

![image](https://cloud.githubusercontent.com/assets/1634990/25608189/d030037a-2ece-11e7-90c1-6a93279e0c0c.png)

In all other browsers I've tested, it looks normal. Here's Chrome:

![image](https://cloud.githubusercontent.com/assets/1634990/25608224/f5c2fc14-2ece-11e7-85dc-4497c36900b4.png)

**Comment by davechu** [comment]
Hi, I just took a look at this.... Firefox isn't liking the white-space line below, I reckon. Taking that out made it look like the Chrome scenario.

`.pure-menu-horizontal {
    width: 100%;
    white-space: nowrap;
}`

**Comment by redonkulus** [comment]
@davechu want to open a PR with the fix?

**Comment by bedhed** [comment]
Thanks @davechu for the hint, @redonkulus here is one PR with a drastic approach : removing the white-space line altogether. IMO the cleanest fix.

**Comment by magikstm** [comment]
I can't reproduce this issue on Windows 7 x64 with Firefox 63.0.

Page works well in:
- IE11 11.90.0
- Chrome 70.0

**Comment by lkraav** [comment]
I confirm, layout seems to be fixed right now, and while the structure might have other general problems, it's not the topic of this issue.
