### ISSUE TITLE
<label> text baseline misaligned

### ISSUE THREAD

**Issue by TheRealMarnes** [pure-css/pure#651]
I'm getting this in my personal project as well as on purecss.io itself.

![2017-06-02_15-08-51](https://cloud.githubusercontent.com/assets/3950300/26727071/a00c2bd4-47a5-11e7-9ecf-98ade4417fe4.png)

Rustles my jimmies...

**Comment by redonkulus** [comment]
@TheRealMarnes so the checkbox is misaligned?

**Comment by TheRealMarnes** [comment]
No no, look at the "remember me" text, then at the text on the input elements. Labels are displayed slightly elevated from the baseline everything else respects.

**Comment by redonkulus** [comment]
I see. Its minor but I do see what you are saying. Is this consistent across browsers? If so, I would be open to a PR to fix. Otherwise, if its just one browser, it may be difficult to fix correctly.

**Comment by TheRealMarnes** [comment]
Well it happens in vivaldi too:
![image](https://cloud.githubusercontent.com/assets/3950300/26740917/c19f1004-47d7-11e7-9589-953687dbfcf9.png)

And in edge:
![image](https://cloud.githubusercontent.com/assets/3950300/26740948/e1648996-47d7-11e7-8eaf-ac22a1449261.png)

**Comment by redonkulus** [comment]
If you want and have time, please open a PR to fix. That would be appreciated.

**Comment by TheRealMarnes** [comment]
As in, I have to figure out the solution?

**Comment by TheRealMarnes** [comment]
All I know that sort of works is setting vertical-align:baseline on everything that isn't the label... which just screws up other things

**Comment by redonkulus** [comment]
> As in, I have to figure out the solution?

Basically.

> All I know that sort of works is setting vertical-align:baseline on everything that isn't the label... which just screws up other things

Ya thats why I'm hesitant to try and fix it. Given the different is a pixel or 2 and hard to notice. Thats why I was suggesting that if it bothers you enough, you may want to try and fix it :)

**Comment by TheRealMarnes** [comment]
I hate being cursed with my attention to details :( I cannot unsee a 1px offset... It's like a bright green dead pixel in the middle of all black to me

**Comment by redonkulus** [comment]
I hear ya, I have that OCD as well. Just no time to do in this particular issue right now.
