### ISSUE TITLE
Error on purecss.io

### ISSUE THREAD

**Issue by jcoonrod** [pure-css/pure#682]
### Description

The "Customization Page" of purecss.io states that the main pure-min.css file is a responsive rollup, but it is not - one has to combine two files.
### Expected behavior
Accurate instructions to new users.

### Actual behavior
Inaccurate information.

### Steps to Reproduce

1. Visit https://purecss.io/customize/
2. Read first section on rollups
3. [and so on...]

### Environment

* 1.0.0:
* Browser name and version: any
* Link to your project or example: https://purecss.io/customize/

**Comment by redonkulus** [comment]
@jcoonrod Which text specifically? I re-read it a few times and couldn't find the error you mention.
