### ISSUE TITLE
`pure-controls` class'margin-left is 11em, but betweed 691px and 1007px screen, use the class cannot align with `pure-control-group`?

### ISSUE THREAD

**Issue by Dawnight** [pure-css/pure#685]
### there are two pictures
when the screen width is great than 1007px or less than 691px , the `pure-controls` can normal, and if I change the `margin-left: 0;`, it will be OK, and align  with class `pure-control-group`. but when I change the screen width again, oh, all is broken..

now I wanna make the `pure-controls` **always align** with class `pure-control-group`.

so,  I wanna know, can next version  resolve this problem? or, I need custom my style  when I use `pure-controls` class?

![01](https://user-images.githubusercontent.com/22065941/34288699-b715f232-e729-11e7-8258-74fcf7ae9aeb.png)
![02](https://user-images.githubusercontent.com/22065941/34288705-bec80ad8-e729-11e7-8731-bdd8996bf941.png)

**Comment by redonkulus** [comment]
@Dawnight do you have a codepen sample or URL that demonstrates this issue? 

In the meantime, you can define your [own responsive grid break points](https://purecss.io/tools/#generating-custom-responsive-grids) to handle different screen widths.
