### ISSUE TITLE
How do I not show the down arrow in a dropdown menu?

### ISSUE THREAD

**Issue by Timenizer** [pure-css/pure#689]
I am switching my css frame to Pure CSS. How do i surpress the down arrow in the dropdown menu?

**Comment by magikstm** [comment]
Is your site viewable online?

**Comment by redonkulus** [comment]
@Timenizer it comes from the [menu-dropdown.css](https://github.com/pure-css/pure/blob/master/src/menus/css/menus-dropdown.css#L28), there is no way to disable it from pure. You would have to overwrite the styles in your application.
