### ISSUE TITLE
Documented class "1-box" is not a valid css name

### ISSUE THREAD

**Issue by cmcginty** [pure-css/pure#693]
Defining a CSS class named `1-box` does not work in Chrome, nor is it valid CSS:

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); **they cannot start with a digit**, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

https://www.w3.org/TR/CSS21/syndata.html#characters

**Comment by redonkulus** [comment]
@cmcginty where did you see `1-box` defined in Pure?

**Comment by cmcginty** [comment]
Sorry, this was a my mistake, it was on the https://purecss.io/grids/ page. I see now it is actually `l-box` not `1-box`.

**Comment by redonkulus** [comment]
Ok no problem. Ya it’s hard to tell the difference.
