### ISSUE TITLE
IE8 compatibility with responsive grids?

### ISSUE THREAD

**Issue by tconroy** [pure-css/pure#694]
Hello!

The readme lists IE8+ as being supported, however I'm curious how this can be, since the grid system uses flex layout that isn't supported by IE8.

**Comment by redonkulus** [comment]
The [docs mention](https://purecss.io/grids/#pure-responsive-grids) the use of an `grids-responsive-old-ie.css` file you can use to make it work in older browsers.

**Comment by tconroy** [comment]
Hey @redonkulus, guess I missed that - apologies! Thanks for clearing that up.
