### ISSUE TITLE
pure-g and letter-spacing

### ISSUE THREAD

**Issue by edica** [pure-css/pure#695]
Do need to use letter-spacing in pure-g?
.pure-g { letter-spacing: -.31em; ...

We always have to use pure-u-* after pure-g.
If not, the letters stick together.

**Comment by redonkulus** [comment]
Yes it is a requirement to use the `pure-u-*` classes. From the [website](https://purecss.io/grids/):

> **All child elements of a grid must be units**
Child elements contained within an element with a pure-g classname must be a grid unit with a pure-u or pure-u-* classname.
