### ISSUE TITLE
purecss.io is down

### ISSUE THREAD

**Issue by jonathanbell** [pure-css/pure#697]
### Description

Not sure if you are aware or not, but <http://purecss.io/> is not responding in browser.  

### Expected behavior

The website should load.

### Actual behavior

Website does not return a response.

### Steps to Reproduce

1. Open a browser and try to navigate to https://purecss.io/

### Environment

Windows 7, Chrome

**Comment by redonkulus** [comment]
It works for me on mac/chrome, still an issue?

**Comment by jonathanbell** [comment]
Apologies! I just checked and it is working for me in FF and IE. I'm at work so perhaps a plugin is blocking this domain!?? The error displayed is: "The connection was reset."

**Comment by jonathanbell** [comment]
PS Actually.. Apologies again! However now I see: "Secure Connection Failed" in FF. Is something going on with your SSL cert?

**Comment by KeiroD** [comment]
No issues with SSL here. Still shows as valid here and I'm able to connect via HTTPS.

**Comment by redonkulus** [comment]
Valid for me too. Going to close this one out, looks like its an issue on your end.

**Comment by jonathanbell** [comment]
Apologies for this issue. I guess it is something to do with my organization's network routing.

**Comment by redonkulus** [comment]
No problem, thanks for opening an issue.
