### ISSUE TITLE
Extract AMP-incompatible bits to a separate module?

### ISSUE THREAD

**Issue by vemv** [pure-css/pure#699]
Follow-up of https://github.com/pure-css/pure/issues/675 . Actually I don't quite understand how is that issue 'fixed' - the issue remains. I could remove the problematic code, but at the cost of killing all surrounding build/distribution tooling, having to resort to copy-pasting (right)?

For instance, this is how I use Pure from my Rails app (via https://github.com/rubysamurai/purecss-sass):

![image](https://user-images.githubusercontent.com/1162994/38105702-10dcb2b0-338d-11e8-818f-28f747a588f2.png)

Elegant, modular and integrated. As mentioned, having to quit all this modular goodness just to remove _one_ line of code seems far from ideal!

So, a tempting approach would be to create another module at https://github.com/pure-css/pure/tree/master/src level, called e.g. `amp-incompatible`.

AMP users would simply refrain from importing that module, while the rest would have to either remember to import it (if using Pure modularly), or pull the whole Pure bundle (which would include `amp-incompatible` by default).

Hope it sounds reasonable. I might be missing something, feel free to point it out.

Cheers - Victor

**Comment by vemv** [comment]
Hmm, even assuming my suggestion is followed, there would be still a pain point: the 'star hack' is used, which the AMP validatior will compain about.

``` css
  *letter-spacing: normal;
```

Perhaps one _could_ move all star-rules to the proposed `amp-incompatible` module, but OTOH that might result in a harder-to-maintain codebase (the 'same' rule would be split across two different files).

Perhaps a certain CSS preprocessor (a la reworkcss/rework) can automate this. Not sure myself as I'm not that knowledgeable on the topic.

**Comment by redonkulus** [comment]
So one option I like is another build that publishes amp compatible builds, which would basically remove the `!important` from the `.hidden` style. This would require an update to the Grunt build steps to generate the AMP specific build.
