### ISSUE TITLE
No <link> source specified if you want only grids

### ISSUE THREAD

**Issue by cyberbuff** [pure-css/pure#703]
### Description

On [this](https://purecss.io/grids/#want-to-just-use-grids) page, the text says: "Just include this `<link>` element in your `<head>`." However, the example that follows do not specify any `<link>` tag. 

### Expected behavior
The example should include a `<link>` tag pointing a stylesheet that only contains girds.

### Actual behavior
The example does not include any `<link>` tag.

### Steps to Reproduce
Can be found [here](https://purecss.io/grids/#want-to-just-use-grids)

### Environment
All browsers.

**Comment by redonkulus** [comment]
Thanks for the report. I see the link tags on my browser. What device and browser are to using?

**Comment by cyberbuff** [comment]
I swear I saw no links there yesterday. But looks okay now. I don't know, may be I was too burned out yesterday. Anyway, closing the issue. All okay here.
