### ISSUE TITLE
There isn't LICENSE.md file in repository but  link of readme shows it.

### ISSUE THREAD

**Issue by TYuto** [pure-css/pure#706]
### Description

[Description of the bug or feature]
There isn't LICENSE.md file in the repository but the [link](https://github.com/pure-css/pure/blob/master/LICENSE.md) of readme shows it.

thank you.

**Comment by redonkulus** [comment]
Thanks for the report. I’ve fixes it in https://github.com/pure-css/pure/commit/df65d837fcdafdac74d4552288646558519b8a86
