### ISSUE TITLE
purpose of  button hover/focus opacity

### ISSUE THREAD

**Issue by garretwilson** [pure-css/pure#707]
I notice for button hover/focus state, you have the following code:

```css
filter: alpha(opacity=90);
```

What's interesting is that for the disabled state, you have both the `filter` and `opacity`.

```css
filter: alpha(opacity=40);
opacity: 0.40;
```

I assume the `filter` is for legacy compatibility. So why doesn't the normal hover/focus state have an `opacity` designated?

And what is the purpose of this to begin with? Are you making the entire button partially see-through? Was that intended? Or did you mean to just make the color lighter somehow?

I don't know that this is a bug; I'm just curious.

**Comment by redonkulus** [comment]
This code was before my time. I don’t think it was meant to make see through, but to slightly change the color. Maybe there was some reason to use this in the past for older browsers.

**Comment by garretwilson** [comment]
So looking back at the code, I think that for the hover/focus state the `filter: alpha(opacity=90)` was a fallback for the `linear-gradient` on the `background-image`:

```css
/* csslint ignore:start */
filter: alpha(opacity=90);
/* csslint ignore:end */
background-image: linear-gradient(transparent, rgba(0,0,0, 0.05) 40%, rgba(0,0,0, 0.10));
```

On the disabled state, however, the `filter: alpha(opacity=40)` was a fallback for the `opacity: 0.40`:

```css
/* csslint ignore:start */
filter: alpha(opacity=40);
/* csslint ignore:end */
opacity: 0.40;
```

So in each case the `filter: alpha(…)` was a fallback for something. I no longer think think the missing `opacity` in the first rule was a mistake, because the filter was a fallback for the linear gradient.

I doubt the `filter: alpha(…)` is even necessary anymore, but at least now I understand better why it was there.
