### ISSUE TITLE
Patternlab Starter kit

### ISSUE THREAD

**Issue by absalomedia** [pure-css/pure#709]
### Description

In order to increase awareness & usage of Pure, perhaps create & maintain a [Patternlab](https://patternlab.io/) starterkit?

### Expected behavior
Pattern library display for Pure & any updates

**Comment by absalomedia** [comment]
I'm working on it now
https://github.com/absalomedia/starterkit-mustache-pure

**Comment by redonkulus** [comment]
This is the first I’ve heard of Patternlab. What maintenance is involved?
