### ISSUE TITLE
KeyCDN mirror not working

### ISSUE THREAD

**Issue by dmhendricks** [pure-css/pure#710]
### Description

The [KeyCDN](https://www.keycdn.com/) mirror for Pure listed on the [Alternate CDNs](https://purecss.io/customize/#rollups) page doesn't seem to be working.

### Expected behavior

Assets should load with GET request.

### Actual behavior
Returns NXDOMAIN.

### Steps to Reproduce

1. Open browser.
2. Visit the listed URL: https://opensource.keycdn.com/pure/1.0.0/pure-min.css

### Environment

- Pure version: 1.0.0
- Browser name and version: Chrome/69.0.3497.100, Intel Mac OS X 10.13.6
- Link to example: https://opensource.keycdn.com/pure/1.0.0/pure-min.css

**Comment by redonkulus** [comment]
I'm not sure if this is automatically setup based on when we publish or if someone in the community did this. You can contact their support to see if its an issue on their end. Also this ticket should probably be opened in the pure-site repo to track it. Although I don't think there is much I can do on my end.
