### ISSUE TITLE
Pure CSS blocked by Firefox anti-tracking

### ISSUE THREAD

**Issue by LorenzoAncora** [pure-css/pure#711]
Just a note to let you know that the following resources are blocked by Mozilla Firefox [anti-tracking protection](https://developer.mozilla.org/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default):

- http://yui.yahooapis.com/pure/0.6.0/pure-min.css
- http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css
- http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css

All sites that rely on these resources must then update Pure CSS and switch to a different CDN.

**Comment by redonkulus** [comment]
@LorenzoAncora We [recommend](https://purecss.io/customize/) using unpkg.com as the CDN to load Pure from, you shouldn't need to use the yahooapis.com domain anymore.

**Comment by LorenzoAncora** [comment]
One wonders why Mozilla Firefox has blocked the Yahoo CDN used by Pure CSS.
This was just a note to let you know that the CDN is blocked: _all_ the sites that use it now are no longer displayed correctly in Mozilla Firefox.

> @LorenzoAncora We recommend using unpkg.com as the CDN to load Pure from, you shouldn't need to use the yahooapis.com domain anymore.

I used Pure also because it was hosted / maintained by Yahoo.
This new repository is maintained by a private individual named _Michael Jackson_, not Yahoo. Its only stated purpose is to host JavaScript for npm (not CSS) but it is not supported by npm, Inc.

You are delegating the security of a Yahoo product to a private individual? :-/

**Comment by redonkulus** [comment]
If you are not comfortable using unpkg then you can use any of the other CDNs that we suggest on our website. The yahooapis site is no longer recommended and has been removed from our site.

**Comment by LorenzoAncora** [comment]
Thank you.
