### ISSUE TITLE
Buttons font-size unit

### ISSUE THREAD

**Issue by rflw** [pure-css/pure#722]
### Description

Why there is ```100%``` instead of ```1em``` for button ```font-size```?
Padding for this element is defined in ```em``` unit so why ```font-size``` is in ```%```?

### Expected behavior
```
.pure-button {
  // ...
  font-size: 1em;
  // ...
}
```

### Actual behavior
```
.pure-button {
  // ...
  font-size: 100%;
  // ...
}
```

**Comment by lkraav** [comment]
What does `git blame` say, are you equipped to take a look?

**Comment by rflw** [comment]
[reference to font-size: 100% (blame)](https://github.com/pure-css/pure/blame/master/src/buttons/css/buttons.css#L5)
This line was added 6 years ago. I think units should be standardized currently.

**Comment by lkraav** [comment]
Indeed, I can't really point out the logic behind `font-size 100%` there.

I'm not even sure CSS framework should be setting a `font-size` here - because it's an inherited property, `1em` would just repeat what was already there.

**Comment by rflw** [comment]
Your're right and I'm thinking that ```font-size``` in this case is unnecessary too because it's inherited.
This property should be removed.
