### ISSUE TITLE
menu does not work on local pc

### ISSUE THREAD

**Issue by djary** [pure-css/pure#725]
menu does not work on local pc

as you can see in image https://imgur.com/wz10AII  menu is ruleless in my pc

but i run the code on codepen https://codepen.io/djary/pen/EGOpYZ and work fine ! (all css and js code included).

Why does this happen? Did I make a mistake?

* Pure version: 1.0.0
* Browser name and version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by magikstm** [comment]
Did you confirm that all scripts load properly locally with Chrome's console and Network tab in the devtools?

**Comment by alelasantillan** [comment]
The same is happening to me in my own server. 
The menu with sub-menus is not showing the sub menus.
The page has the following code (following the tutoral at https://purecss.io/menus/):

<!doctype html>
<html>
<head>
<title>Maitai</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">


<style>
.custom-restricted-width {
    /* To limit the menu width to the content of the menu: */
    display: inline-block;
    /* Or set the width explicitly: */
    /* width: 10em; */
}
</style>
</head>

<div class="pure-menu custom-restricted-width">
    <ul class="pure-menu-list">
        <li class="pure-menu-item pure-menu-selected"><a href="#" class="pure-menu-link">Flickr</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Messenger</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Sports</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Finance</a></li>
        <li class="pure-menu-item pure-menu-has-children">
            <a href="#" id="menuLink1" class="pure-menu-link">More</a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Autos</a></li>
                <li class="pure-menu-item"><a href="#" class="pure-menu-link">Flickr</a></li>
                <li class="pure-menu-item pure-menu-has-children">
                    <a href="#" id="menuLink1" class="pure-menu-link">Even More</a>
                    <ul class="pure-menu-children">
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Foo</a></li>
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Bar</a></li>
                        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Baz</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>
