### ISSUE TITLE
Safe to use in new project?

### ISSUE THREAD

**Issue by cliffordh** [pure-css/pure#727]
I really like how lean this framework is. I also like that it supports IE11, which is almost 10% of my users. But, is this "safe" to use and supported in any way? Or, have developers gone to a different fork or framework entirely?

**Comment by redonkulus** [comment]
It's basically mature and there hasn't been much active development besides some minor bug fixes. It's still safe to use, as it is not that opinionated. 

As for the outdated dependencies, no reason to move off Grunt unless there is a pressing need. Chasing shiny new tools isn't always necessary. We no longer support Bower. Normalize could be updated but I'd be interested to see what the benefits are. Upgrading this would probably bump the major version if there are a bunch of breaking changes.

**Comment by jschatz1** [comment]
I mean there are still IE 8 conditional comment tags in the demos. There are button alignment issues in the current version of firefox. This is just the stuff I am seeing within the first few minutes.

**Comment by inliquid** [comment]
It's of 2013. 6 years with no major improvements. There even no modals -  invent yourself (but it's ok if you stuck in 2013). Menus with dummy JS (same). Old normalize.css. Such "framework" you can write yourself in a couple of days.

**Comment by svanstrom** [comment]
I'm here asking myself the same question…

In theory I love the idea behind this project, and would love to use it; but it feels really stale/outdated, and it doesn't exactly help that the http://blog.purecss.io/ has been more or less dead for 3-4 years now.

Who's in charge, and are they open to having the project properly revitalised?

**Comment by redonkulus** [comment]
There hasn’t been a dedicated team working on this for 4 years. If the community wants to migrate the dependency to whatever is modern nowadays, upgrade normalize etc. I’m all for it. I’d love to see this project thrive. Again, it’s up to the community to push it forward. There are no resources at Yahoo that will do this. Generally, people want someone to do it, but just not themselves. 

So feel free to open a PR with all the changes to modernize this project. I can even give commit access for those that are interested and dedicated to working on it. 

I should probably put this in the readme since we get this question every few months.

**Comment by svanstrom** [comment]
> If the community wants to migrate the dependency to whatever is modern nowadays, upgrade normalize etc. I’m all for it. I’d love to see this project thrive. 

> I should probably put this in the readme since we get this question every few months.

If I'd seen that in the blog on the website it would have saved me a couple of months of having an open tab to keep track of things. ;-)

Right now I so don't have the time for a new project, but it would fit within a startup that I'm currently busy with; so I don't rule out getting actively involved later this year.

**Comment by redonkulus** [comment]
Ya I don't even have access to the blog to update it haha, I will need to reach out to the old maintainers to get access.

**Comment by redonkulus** [comment]
FYI I've updated the Roadmap issue to include other tasks to enhance Pure - https://github.com/pure-css/pure/issues/692. Please add comments about other features, migrations or things that should/could be done.

**Comment by jon49** [comment]
I used PureCSS back in the day and it was great. It is sad to see it die or only relevant if you are building for really old browsers. There are minimal CSS framework alternatives out there though. Like:

https://picnicss.com
https://milligram.io/

Possibly others?

**Comment by lkraav** [comment]
Indeed, it would make sense to join forces, rather than fragment further. Among the most prevalent open source development problems.

**Comment by I-CRE8** [comment]
> It's basically mature and there hasn't been much active development besides some minor bug fixes. It's still safe to use, as it is not that opinionated.

This is why I use Pure, I prefer boring and stable for my production environment. Any customer I don't support is a potential sale lost.
