### ISSUE TITLE
Normalize.css

### ISSUE THREAD

**Issue by cliffordh** [pure-css/pure#728]
I see that Normalize.css is at version 8.01 but Pure uses Normalize 3.0 and was last updated in 2015. Does this need to be upgraded? If so, how?

**Comment by redonkulus** [comment]
What changed between v3 and v8? We can upgrade but the reason should be sound. We would also need to bump the major version as that could cause sites to break.

**Comment by lkraav** [comment]
Even though I haven't kept a close eye on normalize changelog specifics, browser peculiarities do change over time, no? I would think they've had solid reasons for version updates :)

**Comment by redonkulus** [comment]
Fair enough. If anyone wants to upgrade and see what needs to be fixed (if anything), please feel free.

**Comment by co16353sidak** [comment]
Hi, I am new to this repo. would love to contribute if this is available. @redonkulus

**Comment by redonkulus** [comment]
@co16353sidak Feel free to fork the repo, upgrade normalize.css and test is across browsers (Chrome, Firefox, Edge, Safari - mobile and desktop) to see what breaks and what doesn't.

**Comment by lkraav** [comment]
...and implement an automated headless test suite while you're at it, Puppeteer-based or themsuch. Much awesome, tyvm :)

**Comment by redonkulus** [comment]
Haha agreed. Are snapshot diff testing reliable enough for automation?

**Comment by co16353sidak** [comment]
@ikraav @redonkulus
:+1

**Comment by lkraav** [comment]
I believe https://www.cypress.io has been the most :eyes: :eyes: that I've recently come across, but have yet to implement it myself.

**Comment by redonkulus** [comment]
FYI I've updated the Roadmap issue to include other tasks to enhance Pure - https://github.com/pure-css/pure/issues/692. Please add comments about other features, migrations or things that should/could be done.

**Comment by borisov87** [comment]
Normalize changelog

https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md
