### ISSUE TITLE
multilevel Dorpdowns in horizontal navbar doe not work

### ISSUE THREAD

**Issue by JeanLucLejoly** [pure-css/pure#730]
### Description

I do like the simplicity of the pure css approach. I tryed Bootstrap and foundation with my rails apps, Pure makes it way simpler to maintain with less mess and fighting the opinions of the systems. The only issue I have to to do multilevel horizontal menus  One level works great, multilevels however, the opened up submenu overlays the main menu, and then the access to the items underneath it is gone. Any ideas, anybody?

**Comment by haohanyang** [comment]
I have encountered the same problem, hoping someone to get it fixed.
