### ISSUE TITLE
Need to fix that tfoot be distinguished from tbody.

### ISSUE THREAD

**Issue by kimulaco** [pure-css/pure#731]
Hi.
This is a great CSS framework!

### Description

When you add tfoot to various tables, the table footer of the same design is displayed.
So I think it is necessary to change the design to distinguish it from tbody.

I read ["Style tfoot elements the same as thead elements."](https://github.com/pure-css/pure/pull/583 ).

I agree that thead and tfoot have different designs.
However, it should be corrected that it can not be distinguished from tbody.

### Expected behavior
It should be designed to distinguish it from tbody.

### Actual behavior

However, it is visually indistinguishable from tbody and may not have a border.

Capture is an example of adding tfoot to the document page table.

https://purecss.io/tables/

![](https://user-images.githubusercontent.com/11986753/56845041-a968ba80-68f5-11e9-82a9-9ed7a5d890e1.png)

### Environment

* Pure version: 1.0.0
* Browser name and version: Google Chrome

**Comment by geekosupremo** [comment]
I may be misunderstanding, but this seems like something that would generally be left to the individual designer/developer. The Pure tries to be as un-opinionated as it can so that the end user can express their own style with minimal overrides.

**Comment by redonkulus** [comment]
Agreed, I would prefer to leave to developers/apps.
