### ISSUE TITLE
Example: Cards? Quoteblocks? MessageBlocks? Codeblocks?

### ISSUE THREAD

**Issue by DonaldTsang** [pure-css/pure#735]
I saw on the website that there are no cards at all in the example/tutorials.
Since all three of these concepts are basically the same common format, is it possible to make something out of it?

**Comment by redonkulus** [comment]
@DonaldTsang not a bad idea, do you want to contribute the example?

You can open a PR on the [website repo](https://github.com/pure-css/pure-site). Closing this since it is not an issue for pure.

**Comment by DonaldTsang** [comment]
@redonkulus got it, not too experienced with tampering with CSS but I definitely will try. For code blocks `<code>` is used. There is also `<aside>` but it looked way too highlighted for cards and codeblocks.
