### ISSUE TITLE
Add some animations using paperjs

### ISSUE THREAD

**Issue by NitinMadhukar** [pure-css/pure#737]
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Environment

* Pure version:
* Browser name and version:
* Link to your project or example:

**Comment by DonaldTsang** [comment]
The development team expects everything to be lightweight, so maybe you can create an add-on layer separate from the main repo to make it closer to Bulma and Bootstrap (except no-JS browsers are slightly better)

**Comment by magikstm** [comment]
I suggest closing this as it doesn't seem to fit the scope of the project.
