### ISSUE TITLE
[QUESTION] Slider element (not image slideshow)

### ISSUE THREAD

**Issue by AlexFundorin** [pure-css/pure#743]
How do I add a slider with a set range (like, 1-100) and a step value (.1 or 1) to my pure-css  code?
Something like this one: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1MFWceSStOgPmqholFlYP9AE1PMEUUrqZ%2Fsliders-discreteslider-states2.png

**Comment by redonkulus** [comment]
That's going to be custom css you will need to do on top of Purecss since there are no components that do that at the moment. I'm sure there are examples on the web that can help you out.
