### ISSUE TITLE
Implement Automated Dependency Management

### ISSUE THREAD

**Issue by PatOnTheBack** [pure-css/pure#744]
Implement an automated dependency management tool. This can make it easier to manage dependency updates and warn about security vulnerabilities in dependencies.
GitHub has a built in vulnerability scanner in the `Security` tab of this repository.

Another tool that this project could use is https://renovatebot.com/ to automatically create PRs to update dependencies.

**Comment by redonkulus** [comment]
We probably use Githubs built-in dependency bot.

**Comment by PatOnTheBack** [comment]
@redonkulus is the DependaBot and security scanning enabled on this repository?

**Comment by redonkulus** [comment]
Not yet, I need to add the integration.

**Comment by redonkulus** [comment]
@PatOnTheBack dependabot has been added, which will include security scanning.
