### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by mcglonelevi** [pure-css/pure#750]
I have used this CSS framework in a few projects, and I really like it!  I am thinking about using it again in an upcoming project; however, looking at the recent commit and issue activity, it looks like this framework hasn't had much activity recently.

Is this repo still maintained?

**Comment by redonkulus** [comment]
This is the most up to date status of the project https://github.com/pure-css/pure/issues/692.

tl;dr its stable and open to contributions from everyone 😄
