### ISSUE TITLE
range input style

### ISSUE THREAD

**Issue by Antix-Development** [pure-css/pure#753]
### Range Input style

Every single framework I have evaluated (some 40 in the last two weeks) don't style range inputs... they just leave them as the default ugly browser ones. I feel range inputs need their own built in style lovin.

**Comment by magikstm** [comment]
0/40?

I think such styling should be left to the end-user to implement.

It doesn't fit the minimalist, unopiniated and clean design principles that purecss strives for.

**Comment by Antix-Development** [comment]
I can't agree sorry. I feel that every framework that is based around the idea of styling HTML elements should provide some basic customized style to all of the basic HTML elements, and then leave the user to re-style them accordingly.

If Pure wants to be really minimalist then it should drop elements such as template which are arguably used even less than range inputs ;)
