### ISSUE TITLE
Children menu items in verticle menus

### ISSUE THREAD

**Issue by SERA-Eric** [pure-css/pure#755]
### Description

[Description of the bug or feature]
I know this is probably the wrong place, but I am having trouble getting sub-menus to display in vertical menus.  I started with the code available on your web-page, then found this on github.  I could find no place on the web to ask questions.

**Comment by lkraav** [comment]
Questions go to https://gitter.im/yahoo/pure

**Comment by SERA-Eric** [comment]
Thank you.

 

Thanx Eric

 <mailto:Eric@FleetFootFarm.com> Eric@FleetFootFarm.com

865.986.5966 (H)

865.599.3594 (C)

**Comment by yr602294677** [comment]
请问解决了吗？
是子菜单打不开的问题吗
