### ISSUE TITLE
PureCSS Grid Messed Up

### ISSUE THREAD

**Issue by trymeouteh** [pure-css/pure#789]
I cannot figure out why my purecss grid is messed up. This is my code and for whatever reason it when I render it in the browser, it will show the "Thirds" stacked ontop of one another as if z-index is being used.

All I am using for CSS is Purecss 1.0.1. When I use the Purecss CDN this is not the case and the grid works. Am I missing a css file or a dependency?

Code...
```
<html>
     <head>
          <link rel="stylesheet" href="normalize.css" />

          <link rel="stylesheet" href="purecss/base/css/base.css" />
          <link rel="stylesheet" href="purecss/grids/css/grids-core.css" />

          <meta name="viewport" content="width=device-width, initial-scale=1">
     </head>
     <body>
          <div class="pure-g">
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
          </div>

          <hr />

          <div class="pure-g">
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
          </div>
     </body>
</html>
```

[How it looks](https://preview.redd.it/pdbcwm8td0u41.jpg?width=1919&format=pjpg&auto=webp&s=b2946d3fb0e08607ead780596745f8e3ef4859a6)

**Comment by redonkulus** [comment]
@trymeouteh pure bundles normalize inside `base`, can you try removing the normalize `<link />` ?

**Comment by trymeouteh** [comment]
> @trymeouteh pure bundles normalize inside `base`, can you try removing the normalize `<link />` ?

It get the same result except it is not flush to the top-left edge of the screen since there is a "margin" which is normal in a webpage with the body margin is not set to 0.

```
<html>
     <head>
          <link rel="stylesheet" href="purecss/base/css/base.css" />
          <link rel="stylesheet" href="purecss/grids/css/grids-core.css" />

          <meta name="viewport" content="width=device-width, initial-scale=1">
     </head>
     <body>
          <div class="pure-g">
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
          </div>

          <hr />

          <div class="pure-g">
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
          </div>
     </body>
</html>
```

**Comment by redonkulus** [comment]
Can you try using `<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">` instead?

Could also try adding `<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">` too.

**Comment by trymeouteh** [comment]
> Can you try using `<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">` instead?
> 
> Could also try adding `<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">` too.

This does work with normalize.css but why doesn't [PureCSS 1.0.1 download](https://github.com/pure-css/pure-release/releases) not work?

```
<html>
     <head>
          <link rel="stylesheet" href="normalize.css" />

          <link rel="stylesheet" href="purecss/base/css/base.css" />
          <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">

          <meta name="viewport" content="width=device-width, initial-scale=1">
     </head>
     <body>
          <div class="pure-g">
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
          </div>

          <hr />

          <div class="pure-g">
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
          </div>
     </body>
</html>
```

**Comment by redonkulus** [comment]
base.css and grid.css are in the source so it should work. I haven't tried it locally.

**Comment by redonkulus** [comment]
@trymeouteh you have to add the responsive grids file if you want to use the `pure-u-md-*` classes:
```html
<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css" />
```

See the docs here: https://purecss.io/grids/#pure-responsive-grids

**Comment by trymeouteh** [comment]
Why isn't this apart of the PureCSS download?

**Comment by redonkulus** [comment]
@trymeouteh it is, you can see it in https://unpkg.com/browse/purecss@1.0.1/build/, looks for `grids-responsive-min.css`

**Comment by trymeouteh** [comment]
Why wouldn't all of these files be included in the github download? I can download them from unpkg but it takes awhile since I have to open up each file and copy all the code and paste it into a blank notepad file and save it.

**Comment by redonkulus** [comment]
I see so as of v2.0.0, that pure-release repo will no longer be updated. It was used for bower which is deprecated. You can install the `purecss` npm package and get access to all the build files locally. Or use one of the CDN defined in https://purecss.io/customize/

**Comment by trymeouteh** [comment]
Will there be a zip download of all the css source code and min files somewhere? Just like how bootstrap can be downloaded, extracted, copied and pasted into your website and used locally? I do not use npm or Bower.

**Comment by trymeouteh** [comment]
> @trymeouteh you have to add the responsive grids file if you want to use the `pure-u-md-*` classes:
> 
> ```
> <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css" />
> ```
> 
> See the docs here: https://purecss.io/grids/#pure-responsive-grids

I am trying to use 2.0.0 with the grids-responsive.css file and my grid will still not work.

```
<html>
     <head>
          <link rel="stylesheet" href="normalize.css" />

          <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/base.css" />
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/base-context.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/buttons.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/buttons-core.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/forms.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/forms-nr.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/grids.css" /> -->
          <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/grids-core.css" />
          <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/grids-responsive.css" />
          <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/grids-units.css" />
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/menus.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/menus-core.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/menus-dropdown.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/menus-horizontal.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/menus-scrollable.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/menus-skin.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/pure.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/pure-nr.css" /> -->
          <!-- <link rel="stylesheet" href="https://unpkg.com/browse/purecss@2.0.0/build/tables.css" /> -->

          <meta name="viewport" content="width=device-width, initial-scale=1">
     </head>
     <body>
          <div class="pure-g">
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
          </div>

          <hr />

          <div class="pure-g">
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u-1 pure-u-md-1-3">
                    Thirds
               </div>
          </div>
     </body>
</html>
```

**Comment by redonkulus** [comment]
There are a few problems with your snippet.

1. The links to unpkg should be:
```
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/base.css" />
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-core.css" />
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-responsive.css" />
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-units.css" />
```
Notice I removed the "browse" from the URLs.

2. Your responsive grid class should be `pure-u` not `pure-u-1. 

<details>
    <summary>This works for me locally</summary
<pre>
<html>
     <head>
          <link rel="stylesheet" href="normalize.css" />

          <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/base.css" />
          
          
          
          
          
          
          <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-core.css" />
          <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-responsive.css" />
          <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-units.css" />
          
          
          
          
          
          
          
          
          

          <meta name="viewport" content="width=device-width, initial-scale=1">
     </head>
     <body>
          <div class="pure-g">
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
               <div class="pure-u-1-3">
                    Thirds
               </div>
          </div>

          <hr />

          <div class="pure-g">
               <div class="pure-u pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u pure-u-md-1-3">
                    Thirds
               </div>
               <div class="pure-u pure-u-md-1-3">
                    Thirds
               </div>
          </div>
     </body>
</html>
</pre>
</details>

**Comment by trymeouteh** [comment]
Now it works! Thank you sir.

Is the "-1" removed from 2.0.0? I know 2.0.0 was released today so the documentation may not be updated yet but it shows that "pure-u-1" is a class used in responsive grids.

https://purecss.io/grids/#pure-responsive-grids

**Comment by redonkulus** [comment]
Thats on purpose, the description above the example explains why its done that way:

> Next, let's look at a responsive grid. Elements within this grid will be width: 100% on small screens, but will shrink to become width: 33.33% on medium-sized screens and above.

So when the browser is stretched it will be 100%, but when you minimize the browser, it will then take up 33%.

**Comment by trymeouteh** [comment]
Sorry to bother you again. But with this simple grid, it will not stretch out 100% under 567px. How does one have a grid stretch to 100% on small mobile screen between 320-567px?

`<html>
<head>
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/base.css" />
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-core.css" />
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-responsive.css" />
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.0/build/grids-units.css" />

<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="pure-g">
     <div class="pure-u pure-u-sm-1-1 pure-u-md-1-3">
          Thirds
     </div>
     <div class="pure-u pure-u-sm-1-1 pure-u-md-1-3">
          Thirds
     </div>
     <div class="pure-u pure-u-sm-1-1 pure-u-md-1-3">
          Thirds
     </div>
</div>

</body>
</html>`

**Comment by redonkulus** [comment]
You will have to add your own breakpoints to make that happen.

**Comment by trymeouteh** [comment]
I will need to create my own media queries for that?

**Comment by redonkulus** [comment]
Yup, Pure comes with some default ones, but cannot satisfy all application use cases.

**Comment by trymeouteh** [comment]
Thank you for all your help!
