### ISSUE TITLE
SHA384 error on homepage

### ISSUE THREAD

**Issue by symac** [pure-css/pure#793]
Right now on https://purecss.io/ the get started example is : 

```html
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.1/build/pure-min.css" 
integrity="sha384-nr8Zg0FGuy2mHjSDEtlFTk1UAYPogC1fcXsXwpshTY+BexlZFHQ99ruU/jL77qd7"
crossorigin="anonymous">
```

But the sha384 does not work. It appears to work with the following change : 
```html
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.1/build/pure-min.css" 
integrity="sha384-QkSsJi6SGgWv5LAx1TdvIDRf8TW5Ui4NVKqDDlK1wY2eKioo7wvYIJvGWFQSFE4U" 
crossorigin="anonymous">
```

**Comment by redonkulus** [comment]
Thanks for the report. When I run the site locally I get the correct sha384, it looks like the [generated files](https://github.com/pure-css/pure-css.github.io/tree/master/start) are not being updated by docusaurus. I will have to debug this more.

**Comment by redonkulus** [comment]
@symac took me a while to figure out that my "browserlist" configuration was only set correctly locally, but not on travis, so the sha384 wasn't accurate based on the built files. I believe it should be fixed now. Please let me know.
