### ISSUE TITLE
Select Dropdown Arrow on Firefox

### ISSUE THREAD

**Issue by trymeouteh** [pure-css/pure#795]
The dropdown arrow on the select tag does not render correctly in the Firefox browser. I am using Firefox 77.0b4 (64-bit) on Linux Mint 19.3. The dropdown arrow does render properly in my Chromium browser.

If you look at the "State" select tag on this page in Firefox, you will see the dropdown arrow is not rendering correctly.
https://purecss.io/forms/#stacked-form

**Comment by redonkulus** [comment]
Thank you for the report. Can you post a screenshot? It looks fine on my mac Firefox version.

**Comment by lkraav** [comment]
It's true, FF76 also displays dropdown arrow rather gimpy 
![image](https://user-images.githubusercontent.com/147228/81640530-707b8500-9427-11ea-815b-1d8d1d291dd7.png)

But looking at CSS cascade, it doesn't seem to be anything Pure is doing (not much).

This looks like a FF core stylesheet bug.

**Comment by redonkulus** [comment]
Ya it doesn't look like there is much we can do on the Pure side. You can try filing a ticket for Firefox and in the meantime fix it in your sites stylesheet (if possible).
