### ISSUE TITLE
"Pure - Layouts" page image hyperlinks do not work

### ISSUE THREAD

**Issue by n1000** [pure-css/pure#796]
### Description / Issue

The layouts page here: https://purecss.io/layouts/ has an image link to the layout, a "View" link, and a "Source" link.

The "View" and "Source" buttons work fine, but clicking the image link does not seem to work in Firefox or Chrome (I get an "Oops, page not found" error page).

### Steps to Reproduce

1. Visit https://purecss.io/layouts/
2. Click the "Blog" layout image link (or other layout image link)

### Environment
* Pure version: https://purecss.io/layouts/
* Browser name and version: Firefox 76.0.1, Chrome 81.0.4044.138
* Link to your project or example: https://purecss.io/layouts/

**Comment by redonkulus** [comment]
@n1000 thanks for the report, I've fixed it and it should be live on the site now.
