### ISSUE TITLE
Download link to v2.0.3.zip gives 404

### ISSUE THREAD

**Issue by masoudd** [pure-css/pure#797]
The download link in https://purecss.io/start/ which leads to:

https://github.com/pure-css/pure-release/archive/v2.0.3.zip

gives 404. It is because the pure-release repo is deprecated. I think it should be changed to
https://github.com/pure-css/pure/archive/v2.0.3.zip

**Comment by redonkulus** [comment]
@masoudd Thanks for the report! I've changed the link and its live on the site now.
