### ISSUE TITLE
Links to responsive grids css files given in site examples point to version 1.0.1

### ISSUE THREAD

**Issue by masoudd** [pure-css/pure#798]
In these two places:

- https://purecss.io/start/#responsive-grids
- https://purecss.io/grids/#pure-responsive-grids

It gives this code:
`<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">`

They both link to older version 1.0.1

**Comment by redonkulus** [comment]
Changes are live now. Thanks for reporting.
