### ISSUE TITLE
Site menu hamburger button doesn't work

### ISSUE THREAD

**Issue by masoudd** [pure-css/pure#800]
### Description
The menu for purecss.io doesn't work when it becomes a hamburger

### Expected behavior
It should work like in https://purecss.io/layouts/side-menu/

### Actual behavior
Nothing happens when tapped or clicked on

### Steps to Reproduce

1. Go to https://purecss.io on a phone or desktop
2. If on desktop, resize window so the menu turns into a hamburger
3. tap or click on the hamburger menu button

### Environment

* Pure version: 2.0.3 I think
* Browser name and version: Tested on android {firefox, chrome}, windows {firefox, chrome}, linux {firefox} all latest version.

**Comment by redonkulus** [comment]
@masoudd thanks for the issue, the fix is live now.
