### ISSUE TITLE
Bug in example layout "Responsive Side Menu" with purecss@2.0.3

### ISSUE THREAD

**Issue by crsqq** [pure-css/pure#803]
### Description

Example layout "Responsive Side Menu" does not work as expected with `purecss@2.0.3/build/pure-min.css`

### Expected behavior
 layout [side-menu](https://purecss.io/layouts/side-menu/) should have the same behavior if the stylesheet is replaced by the one currently features on the main page.

### Actual behavior
If the stylesheet in the layout [side-menu](https://purecss.io/layouts/side-menu/) is changed to the one with is listed on the homepage `purecss@2.0.3/build/pure-min.css`, then the pure-menu-item for every entry is as high as the complete page.
This results in an unnecessary scrollbar and its hard to see that there exist other menu entries in addition to the first.

See

![ezgif-4-0e1dcdaba3ec](https://user-images.githubusercontent.com/4514040/84779249-73e4cc00-afe4-11ea-817c-6c3fc0eb861a.gif)

### Steps to Reproduce

1. Copy source from  layout [side-menu](https://purecss.io/layouts/side-menu/) 
2. replace     `<link rel="stylesheet" href="/css/pure/pure-min.css">` by `<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/pure-min.css"
        integrity="sha384-cg6SkqEOCV1NbJoCu11+bm0NvBRc8IYLRGXkmNrqUBfTjmMYwNKPWBTIKyw9mHNJ" crossorigin="anonymous">`

See file attached.

### Environment
* Pure version: 2.0.3
* Browser name and version: Firefox 77, Chrome 83

[pureSidebar.html.zip](https://github.com/pure-css/pure/files/4786759/pureSidebar.html.zip)

**Comment by redonkulus** [comment]
@crsqq Thanks for the report. Is the pure-min.css from CDN loading correctly? Does the browser display any errors in the console?

**Comment by crsqq** [comment]
`pure-min.css` loads correctly and there are no errors listed in the console.
