### ISSUE TITLE
BT Update V4.5

### ISSUE THREAD

**Issue by arcanisgk** [pure-css/pure#804]
this project is abandoned???

support BT v4.5??

**Comment by redonkulus** [comment]
@arcanisgk what is BT?

**Comment by arcanisgk** [comment]
> @arcanisgk what is BT?

Bootstrap documentation say that this css can co-work with this... but up to v3.7 XD

**Comment by redonkulus** [comment]
I don't personally use bootstrap and when Pure was originally created, it was tested with an older version of BT. If you would like to try this with the latest BT and see if there are issues that would help. Please open a PR if are willing to test it out.
