### ISSUE TITLE
Styling file upload button

### ISSUE THREAD

**Issue by karllhughes** [pure-css/pure#812]
### Description

I think it would help with consistency if the framework styled file upload buttons.

### Expected behavior
I expected file upload buttons to look like the rest of the Pure CSS buttons, but they do not.

### Actual behavior
Here's what an actual file upload button looks like on my computer:
<img width="238" alt="Screen Shot 2020-08-23 at 7 28 24 AM" src="https://user-images.githubusercontent.com/1103622/90978279-464f5e00-e512-11ea-88f4-18c4ecc65734.png">

Compared with a typical Pure CSS button:
<img width="166" alt="Screen Shot 2020-08-23 at 7 28 36 AM" src="https://user-images.githubusercontent.com/1103622/90978286-4ea79900-e512-11ea-9402-42ac10091b1b.png">

### Steps to Reproduce

1. Import Pure CSS using the given instructions
2. Create a form with the `file` input type: `<input type="file" name="file" multiple="multiple" />`
3. Check out the styling.

### Environment

* Pure version: 2.0.3
* Browser name and version: Chrome 84.0.4147.135
* Link to your project or example: N/A

**Comment by redonkulus** [comment]
Good idea, in the past browsers were inconsistent in styling this button, deferring to the default OS styles. Do modern browsers allow this to be styled now?

**Comment by redonkulus** [comment]
In my 2 minutes of googling, it looks like you can hide the input and use the before selector to style it that way: https://css-tricks.com/snippets/css/custom-file-input-styling-webkitblink/

If you want to try this out and open a PR I would be willing to review and pull it in.

**Comment by karllhughes** [comment]
It seems that the current best practice is to hide the ugly file input button and use a custom-styled label to replace it: https://www.benmarshall.me/styling-file-inputs/

This is accessible and works across all browsers, but I'd call anything that involves hiding default behavior a bit of a hack.

I'll play around with it and make a PR sometime in the next couple weeks. Thanks!

**Comment by karllhughes** [comment]
Unfortunately, both the two methods we used have their drawbacks:

- Neither one shows the name of the file
- Both end up having some trouble with accessibility
- It ends up getting pretty hacky to fix all the problems - even just on Chrome

Philosophically, it seems that PureCSS is trying to stay away from messy hacks or JS to do this kind of stuff, so while I'm going to spend a little more time trying some things, but just wanted to update you on the initial exploration.

**Comment by redonkulus** [comment]
Thanks for digging in. This seems similar to issues I've had in the past. In general, PureCSS tries to avoid any hacks and leaves it up to the apps to implement more specific use cases. If we can do this without hacks and still maintain accessibility than I'm all for it. Otherwise, we can leave it for apps to handle.

**Comment by karllhughes** [comment]
@redonkulus I put together a very minimal example solution, but it still lacks the file display name. Being an incomplete solution, I understand if it doesn't get merged, but I figured I would see what you thought.
