### ISSUE TITLE
 Local Install on a Mac ...?

### ISSUE THREAD

**Issue by gdwaynewarner** [pure-css/pure#815]
### Description

I have been trying to do a local install of Pure-CSS on my Mac running Mac OS X 10.10.5. Going through one of the tutorials, they mentioned a file called "Pure-CSS.min," which I can't find anywhere.

### Expected behavior
Ideally, I should just be able to see the file, no matter which OS I'm using.

### Actual behavior
I just cannot locate the file.

### Steps to Reproduce

1. Download Pure-CSS.zip on a Mac
2. Decompress it
3. Search for the "Pure-CSS.min" file

### Environment

* Pure version: 2.0.3
* Browser name and version: Not applicable
* Link to your project or example: Not applicable

**Comment by redonkulus** [comment]
Which tutorial are you referring to? The github release zip/tarball doesn't have the compiled files. The best way would be to use [npm to install it locally](https://purecss.io/tools/#installing-pure-with-npm).

The contents of the package will have the pure-min.css file you are looking for. You can also use unpkg to [inspect the contents](https://unpkg.com/purecss).

**Comment by gdwaynewarner** [comment]
Thanks, I will give those options a try.
As for the tutorial question, I was following this one:
[https://www.coderepublics.com/Purecss/Purecss-how-to-use.php](url)
