### ISSUE TITLE
Website grids documentation

### ISSUE THREAD

**Issue by TechnologyClassroom** [pure-css/pure#816]
At [the bottom of the grids page of the website](https://purecss.io/grids/#want-to-just-use-grids), it says:

## Want to just use Grids?

Grids is part of the Pure CSS file. However, if you just want Grids and not the other modules, you can pull it down separately. Just include **this** `<link>` element in your `<head>`.

```
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/base-min.css">
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/grids-min.css">
<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/grids-responsive-min.css">
```

Should this section list only one of the links or should `this` be changed to `these`?  I added bold to `this` to highlight where it is in the text.

**Comment by vszhub** [comment]
A typo, I believe. Just change to `these`.

**Comment by redonkulus** [comment]
Fixed by https://github.com/pure-css/pure/pull/817
