### ISSUE TITLE
PureCSS responsive classes nor working

### ISSUE THREAD

**Issue by fabionolasco** [pure-css/pure#823]
### Description
Not able to able to get PureCSS's responsive classes to work.

### Expected behavior
The LG SM MD based classes should kick in when the screen size is changed.

### Actual behavior
Nothing happens.

### Steps to Reproduce
Please check plnkr
https://plnkr.co/edit/Aor9A3wpfeeP2CEY

### Environment
Chrome 87

**Comment by magikstm** [comment]
Try to add this line in the header:
`<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/grids-responsive-min.css" />`

It'll add responsive grids.

Ref: https://plnkr.co/edit/qVjWPxSg03OvU5Lp

Ref: https://purecss.io/customize/

**Comment by redonkulus** [comment]
@magikstm thanks for answering the issue. @fabionolasco please comment if this does not solve your issue.
