### ISSUE TITLE
The necessary activation files are missing pure-css

### ISSUE THREAD

**Issue by maria1186** [pure-css/pure#826]
### Description

The necessary activation files are missing in the download link https://github.com/pure-css/pure/archive/v2.0.3.zip

### Expected behavior
There need to be files grids-responsive.css end pure-min.css

### Actual behavior
and I get it [ download Pure](https://github.com/pure-css/pure) all those files that don't have the ones to activate pure.css

**Comment by redonkulus** [comment]
We do not currently bundles the distributed files in the github release, you can use a [cdn](https://purecss.io/customize/) or install via a [package manager](https://purecss.io/tools/#installing-pure-with-npm). I noticed on our Get Started page we have a link to the URL to mention above, I will remove that link.

**Comment by maria1186** [comment]
I understand. **Thanks for the reply :)**
