### ISSUE TITLE
pure.css doesn't include the responsive grid styles

### ISSUE THREAD

**Issue by reivilibre** [pure-css/pure#827]
According to the documentation on the website, `pure.css` is a roll-up of all the responsive and non-responsive parts of PureCSS.

However, I don't find styles such as `pure-u-md-1-2` in there. I had to include `grids-responsive.css` on top of that, which was confusing.

**Comment by redonkulus** [comment]
Thanks for the issue. Can you share with me where it mentions everything is rolled up?

We probably need to fix the documentation since grid has always been separate.

**Comment by reivilibre** [comment]
Sure; I was reading https://purecss.io/customize/#rollups

> Rollups consist of all the modules in Pure. There are two rollups available - a regular (responsive) one, and a non-responsive one. Choose that one that's right for your project.

**Comment by redonkulus** [comment]
@reivilibre if you want, please feel free to update the docs to more accurately describe what is happening.

The update would be in here: https://github.com/pure-css/pure/blob/master/site/src/pages/customize/index.js

**Comment by redonkulus** [comment]
@reivilibre I've gone ahead and added a note on the page
