### ISSUE TITLE
Responsive Side Menu example does not work on Fennec (Firefox?) for Android

### ISSUE THREAD

**Issue by reivilibre** [pure-css/pure#829]
### Description

The side menu cannot be opened on mobile Firefox (well, this is actually F-Droid Fennec, a fork of Firefox).

Clicking the menu button, e.g. on https://purecss.io/layouts/side-menu/, does not work — the sidebar menu is not able to be opened.

Having opened up a debugger, I notice that the click event's `target` is actually the `<span>` tag, whose ID does therefore not match the menuLink's ID, so the CSS `active` classes are not toggled.

### Environment

* Pure version: Pure v2.0.3
* Browser name and version: Fennec F-Droid 84.1.2 (build #841220) on Android
* Link to your project or example: https://purecss.io/layouts/side-menu/

**Comment by redonkulus** [comment]
Thanks for the report. This is buggy on chrome too. Want to try and PR a fix?
