### ISSUE TITLE
Files and Folders missing from 2.06 release

### ISSUE THREAD

**Issue by MJH1000** [pure-css/pure#884]
pure-2.0.6/src/grids/tests/manual/responsive.html

has the following code but there is no 'build' folder or 'grids-responsive.css' file in the package in any dir

```
    <link rel="stylesheet" href="../../../../build/base.css">
    <link rel="stylesheet" href="../../../../build/grids.css">
    <link rel="stylesheet" href="../../../../build/grids-responsive.css">
```

**Comment by redonkulus** [comment]
@MJH1000 we do not package the same pages in the release, where are you getting these files from?

**Comment by Loafer19** [comment]
in test I think "pure-2.0.6/src/grids/tests/manual/responsive.html"

**Comment by redonkulus** [comment]
These files were meant for development, not to be used with the packaged code. If you clone the repo and run the `build` run script at the repo root, then the files will be generated.
