### ISSUE TITLE
Icons missing from buttons example

### ISSUE THREAD

**Issue by MaciejKus** [pure-css/pure#938]
**Describe the bug**
The Font Awesome icons are not being displayed in the `Buttons with icons` example on https://purecss.io/buttons/

**To Reproduce**
1. open https://purecss.io/buttons/
2. view the buttons in the `Buttons with icons` section

**Expected behavior**
buttons should display icons and text. they are missing the icons.

**Screenshots**

<img width="1399" alt="Screen Shot 2022-01-03 at 3 27 49 PM" src="https://user-images.githubusercontent.com/2653143/147991362-7563374f-80e2-431c-b31b-fdbe9af57997.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: tested on FireFox (95.0.2) and Chrome (96.0.4664.110)

**Comment by redonkulus** [comment]
@MaciejKus Thanks for the report, this was missed when migrating to docusaurus, should be fixed now.
